site_name: Système et réseaux
nav:
    - Accueil: index.md
    - Microsoft: ./pages/microsoft.md
    - Powershell: ./pages/powershell.md
    - VMware: ./pages/vmware.md
   
theme:
    name: mkdocs
    extra_css: extra.css
    
